# 
# This file is written to support the CI/CD process of Gitlab.
# Author: Sumit Sharma
# Maintainer: Sumit Sharma
# E-mail: sumit.sharma@clustervision.com"
# Status: Development
# copyright: Copyright 2022, Luna2 Project [OOD]
# license: GPL
# 

stages:
  - production
  - development

production:
  stage: production
  image: python:3.10.0-alpine
  only:
    - main
  script:
    - python setup.py sdist bdist_wheel
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p $SSH_PASSWORD scp -r -oStrictHostKeyChecking=no dist/* $SSH_USER@$IPADDRESS:$LOCATION

development:
  stage: development
  image: python:3.10.0-alpine
  only:
    - development
  script:
    - python setup.py sdist bdist_wheel
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p $SSH_PASSWORD scp -r -oStrictHostKeyChecking=no dist/* $SSH_USER@$IPADDRESS:$DEV_LOCATION
